eatandrate/attivita/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[\d]+)/$', views.AttView.as_view(), name='detail'),
    url(r'^(?P<pk>[\d]+)/recensisci$', views.recensisci, name='recensisci'),
    url(r'^(?P<pk>[\d]+)/modify$', views.modify, name='modify'),
    url(r'^(?P<pk>[\d]+)/add_image$', views.add_image, name='add_image'),
    url(r'^add/$', views.add, name='add'),
    url(r'^(?P<pk>[\d]+)/delete_image$', views.delete_image, name='delete_image')
]

eatandrate/eatandrate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^admin/', admin.site.urls),
    url(r'^att/', include('attivita.urls', namespace='attivita')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^src/', include('search.urls', namespace='search')),
    url(r'^rec/', include('recensioni.urls', namespace='recensioni')),
]

eatandrate/search/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^simple_search/', views.simple_search, name='simple_search'),
    url(r'^(?P<pk>[\d]+)/simple_results/$', views.simple_results, name='simple_results'),
    url(r'^complex_search/', views.complex_search, name='complex_search'),
    url(r'^(?P<pk>[\d]+)/complex_results/$', views.complex_results, name='complex_results'),
]

eatandrate/users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import logout
from django.contrib.auth.views import login

from users.forms import MyAuthenticationForm
from . import views
from eatandrate.settings import LOGOUT_REDIRECT_URL


urlpatterns = [
    url(r'^(?P<pk>[\d]+)/$', views.user_profile, name='user_profile'),
    url(r'^myprofile/$', views.my_profile, name='my_profile'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^login/$', login, {'template_name': 'registration\login.html',
                             'authentication_form': MyAuthenticationForm}, name="login"),
    url(r'^logout/$', logout, {'next_page': LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^registerowner/$', views.register_owner, name='register_owner'),
    url(r'^modify_profile/$', views.modify_profile, name='modify_profile'),
    url(r'^delete_profile/$', views.delete_profile, name='delete_profile'),
]

eatandrate/search/models.py
from django.db import models
from attivita.models import Tipologia


# Create your models here.
class RicercaSemplice(models.Model):
    """Definisce una ricerca semplice

    Per ricerca semplice intendiamo un semplice ricerca TextField, senza filtro
    sulle tipologie delle attività

    Attibuti:
        testo (CharField)
    """
    testo = models.CharField(max_length=25)


class RicercaComplessa(models.Model):
    """Definisce una ricerca complessa

    Una ricerca è composta da una ricerca testuale per nome, una per città e
    un filtro sulle tipologie a cui l'attività deve appartenere

    Attibuti:
        testo_citta (CharField)
        testo_nome (CharField)
        tipologie (ManyToManyField)
    """
    testo_citta = models.CharField('citta', max_length=25, blank=True)
    testo_nome = models.CharField('nome', max_length=25, blank=True)
    tipologie = models.ManyToManyField(Tipologia, blank=True)

eatandrate/search/forms.py
from django import forms
from django.forms import ModelForm
from .models import RicercaComplessa


class RicercaComplessaForm(ModelForm):
    """Form create dal modello `RicercaComplessa`"""
    testo_nome = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'style': 'width:auto'}))
    testo_citta = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'style': 'width:auto'}))

    class Meta:
        model = RicercaComplessa
        fields = ['testo_nome', 'testo_citta']

eatandrate/search/views.py
from django.contrib import messages
from django.forms import Form
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse

from Custom.TipologieUtils import add_tipe_object
from attivita.forms import TipologieForm
from search.forms import RicercaComplessaForm
from .models import RicercaSemplice, RicercaComplessa
from attivita.models import Attivita


# Create your views here.
def simple_search(request):
    """Controlla form e crea ricerca semplice

    Controlla che il contenuto del form sia valido e in caso affermativo redirige
    alla pagina dei risultati, se no invoca una BadRequest

    :param request: richiesta HTTP
    :return: redirezione o HttpResponseBadRequest
    """
    if request.method != 'POST':
        return HttpResponseBadRequest('Impossibile fare richiesta GET su simple_search view')
    elif request.POST['testo_ricerca'] == '':
        return HttpResponseRedirect(reverse('attivita:index'))

    form = Form(request.POST)
    if form.is_valid():
        if request.POST['testo_ricerca'] != '':
            ricerca = RicercaSemplice(testo=request.POST['testo_ricerca'])
            ricerca.save()
            return HttpResponseRedirect(reverse('search:simple_results', args=(ricerca.id,)))

    print('Qualcosa è andato storto')
    messages.error(request, "Errore nella compilazione form")
    return HttpResponseRedirect(reverse('attivita:index'))


def complex_search(request):
    """Controlla form e crea ricerca complessa

    Controlla che il contenuto dei form sia valido e in caso affermativo redirige alla
    pagina dei risultati, se no invoca mostra errore e redirige a homepage

    :param request: richiesta HTTP
    :return: risposta HTTP
    """
    if request.method != 'POST':
        return HttpResponseBadRequest('Impossibile fare richiesta GET su complex_search view')

    rcf = RicercaComplessaForm(request.POST, prefix='search_info')
    tf = TipologieForm(request.POST, prefix='search_tipologie')
    if rcf.is_valid() and tf.is_valid():
        ricerca = rcf.save()
        add_tipe_object(ricerca, tf)
        return HttpResponseRedirect(reverse('search:complex_results', args=(ricerca.id,)))
    else:
        messages.error(request, "Errore nella compilazione form")
        return HttpResponseRedirect(reverse('attivita:index'))


def show_results(request, results):
    """Mostra risultati della ricerca e mappa con marker per ogni risultato

    :param request: richesta HTTP
    :param results: iterabile contenente i risultati
    :return: Template renderizzato con relativo context
    """
    rcf = RicercaComplessaForm(prefix='search_info')
    tf = TipologieForm(prefix='search_tipologie')
    if not results:
        return render(request, 'search/results.html', {'error_msg': 'Nessun risultato di ricerca',
                                                       'rcf': rcf,
                                                       'tf': tf})
    else:
        results = results[:20]
        for r in results:
            first_result = r
            if r.latitudine and r.longitudine:
                return render(request, 'search/results.html', {'results': results,
                                                               'rcf': rcf,
                                                               'tf': tf,
                                                               'first_result': first_result})
        return render(request, 'search/results.html', {'results': results,
                                                       'rcf': rcf,
                                                       'tf': tf})


def simple_results(request, pk):
    """Calcola risultati di una ricerca semplice

    Si crea una lista contenente tutte le attività che contengo la stringa ricercata
    nel nome, nell'indirizzo o nella città

    :param request: richiesta HTTP
    :param pk: id ricerca
    :return:
    """
    ricerca = get_object_or_404(RicercaSemplice, pk=pk)
    text = ricerca.testo.lower()
    results = list()

    for att in Attivita.objects.order_by('-reputazione'):
        if (text in att.nome.lower()) or (text in att.citta.lower()) \
                or (text in att.descrizione.lower()):
            results.append(att)

    return show_results(request, results)


def complex_results(request, pk):
    """Calcola risultati di una ricerca complessa

    Viene creata una lista contenente tutte le attività che rispettano i filtri
    su nome, città e tipologie contenuti nella ricerca e vengono passati alla
    view `show_results`

    :param request: richiesta HTTP
    :param pk: id ricerca
    :return:
    """
    ricerca = get_object_or_404(RicercaComplessa, pk=pk)
    results = list(Attivita.objects.order_by('-reputazione'))

    # check Nome
    if ricerca.testo_nome != '':
        print('Valuto campo nome')
        results = list()
        pattern = ricerca.testo_nome.lower()
        for attivita in Attivita.objects.order_by('-reputazione'):
            if pattern in attivita.nome.lower():
                results.append(attivita)
        del pattern
        print('Post-nome:', results)

    # check Città
    if ricerca.testo_citta != '':
        print('Valuto città')
        results_nome = results
        results = list()
        pattern = ricerca.testo_citta.lower()
        for attivita in results_nome:
            if pattern in attivita.citta.lower():
                results.append(attivita)
        del results_nome
        del pattern
        print('Post città:', results)

    # check Tipologie
    if ricerca.tipologie.count() > 0:
        for tipo in ricerca.tipologie.all():
            previous_results = results
            results = list()
            for att in previous_results:
                if tipo in att.tipologie.all():
                    results.append(att)

    # ricerca.delete()
    return show_results(request, results)

eatandrate/search/templates/search/results.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Results</title>
{% endblock %}

{% block content %}
<div class="row-fluid" align="center">
    <h1>RICERCA AVANZATA</h1>
</div>
    <div class="row-fluid" align="center">
        <div class=col-md-1></div>
        <div class=col-md-4 style="margin-bottom:50px">
            <form method="post" action="{% url 'search:complex_search' %}">
                {% csrf_token %}
                {{ rcf|as_bootstrap }}
                {{ tf|as_bootstrap }}
                <input class="btn btn-default" type="submit" value="Ricerca" style="padding: 6px 30px">
            </form>
        </div>
        <div class=col-md-6>
            <h3>RISULTATI DI RICERCA</h3>

            {% if error_msg %}
                <p>{{ error_msg }}</p>
            {% else %}
                <ol>
                    {% for r in results %}
                        <li>
                            {{ r.nome }} | {{ r.reputazione | floatformat }}<br>
                            {{ r.citta }}, {{ r.indirizzo }}, {{ r.proprietario.user.username }}<br>
                            <a href="{% url 'attivita:detail' r.id %}">Vai alla pagina dell'attività</a>
                        </li>
                    {% endfor %}
                </ol>
                {% if first_result %}
                    <div id="googleMap" style="margin-bottom: 70px;width:100%;height:290px;top:10px;bottom: 20px;"></div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% if first_result %}
        <script>
            function myMap() {
                var mapProp= {
                  center:new google.maps.LatLng({{ first_result.latitudine }}, {{ first_result.longitudine }}),
                  zoom:10
                };
                var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

                {% for attivita in results %}
                    {% if attivita.latitudine and attivita.longitudine %}
                        var contentString{{ forloop.counter }} =
                            '<h3><a href="{% url 'attivita:detail' attivita.id %}">'
                            + '{{ attivita.nome }}</a></h3>'
                            +'<p>{{ attivita.reputazione | floatformat }}</p>'
                            +'<p>'
                                {% for t in attivita.tipologie.all %}
                                    +'{{ t.nome }} '
                                {% endfor %}
                            +'</p>';

                        var infowindow{{ forloop.counter }} = new google.maps.InfoWindow({
                            content: contentString{{ forloop.counter }}
                        });


                        var marker{{ forloop.counter }} = new google.maps.Marker({
                            position: new google.maps.LatLng({{ attivita.latitudine }}, {{ attivita.longitudine }}),
                            map: map,
                            label: '{{ forloop.counter }}'
                        });

                        marker{{ forloop.counter }}.addListener('click', function() {
                            infowindow{{ forloop.counter }}.open(map, marker{{ forloop.counter }});
                        });
                    {% endif %}
                {% endfor %}
            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgd9efyE6IDhqujcNVWDnJFztZllr21Co&callback=myMap"></script>
    {% endif %}
{% endblock %}