eatandrate/attivita/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[\d]+)/$', views.AttView.as_view(), name='detail'),
    url(r'^(?P<pk>[\d]+)/recensisci$', views.recensisci, name='recensisci'),
    url(r'^(?P<pk>[\d]+)/modify$', views.modify, name='modify'),
    url(r'^(?P<pk>[\d]+)/add_image$', views.add_image, name='add_image'),
    url(r'^add/$', views.add, name='add'),
    url(r'^(?P<pk>[\d]+)/delete_image$', views.delete_image, name='delete_image')
]

eatandrate/eatandrate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^admin/', admin.site.urls),
    url(r'^att/', include('attivita.urls', namespace='attivita')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^src/', include('search.urls', namespace='search')),
    url(r'^rec/', include('recensioni.urls', namespace='recensioni')),
]

eatandrate/notifications/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[\d]+)/reply$', views.reply, name='reply'),
    url(r'^(?P<pk>[\d]+)/delete_answer$', views.delete_answer, name='delete_answer'),
    url(r'(?P<pk>[\d]+)/delete_notification$', views.delete_notification, name='delete_notification')
]

eatandrate/users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import logout
from django.contrib.auth.views import login

from users.forms import MyAuthenticationForm
from . import views
from eatandrate.settings import LOGOUT_REDIRECT_URL


urlpatterns = [
    url(r'^(?P<pk>[\d]+)/$', views.user_profile, name='user_profile'),
    url(r'^myprofile/$', views.my_profile, name='my_profile'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^login/$', login, {'template_name': 'registration\login.html',
                             'authentication_form': MyAuthenticationForm}, name="login"),
    url(r'^logout/$', logout, {'next_page': LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^registerowner/$', views.register_owner, name='register_owner'),
    url(r'^modify_profile/$', views.modify_profile, name='modify_profile'),
    url(r'^delete_profile/$', views.delete_profile, name='delete_profile'),
]

eatandrate/attivita/models.py
"""Definisce i modelli per l'app `attivita`

Modelli:
    Tipologia
    Attività
    Immagine

Funzioni:
    get_upload_path
"""
import os

from users.models import OwnerProfile
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from eatandrate.settings import BASE_DIR
from Custom.Utilities import create_tag_cloud


# Create your models here.
class Tipologia(models.Model):
    """Definisce una tipologia attribuibile ad un'attività

    Attributi:
        nome (CharField): nome della tipologia
    """
    nome = models.CharField('nome', max_length=25, unique=True, default='Useless Tipology')

    def __str__(self):
        """Definisce la stringa per identificare la tipologia

        :return: stringa tipologia
        :rtype str
        """
        return self.nome


class Attivita(models.Model):
    """Definisce un'attività

    Attributi:
        nome (CharField)
        indirizzo (CharField)
        citta (CharField)
        reputazione (FloatField): punteggio dell'attività basato sulle
            recensioni ricevute
        descrizione (TextField)
        proprietario (ForeignKey): chiave esterna al profilo di un proprietario
        tipologie (ManyToManyField): riferimento alle tipologie dell'attività
        latitudine (FloatField)
        longitudine (FloatField)
    :return
    """
    nome = models.CharField('Nome', max_length=50)
    indirizzo = models.CharField('Indirizzo', max_length=50)
    citta = models.CharField('Città', max_length=30)
    reputazione = models.FloatField('Reputazione', default=0,
                                    validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    descrizione = models.TextField('Descrizione', blank=True,
                                   max_length=500)
    proprietario = models.ForeignKey(OwnerProfile, on_delete=models.CASCADE, null=True)
    tipologie = models.ManyToManyField(Tipologia, blank=True)
    latitudine = models.FloatField('Latitudine', blank=True, null=True)
    longitudine = models.FloatField('Longitudine', blank=True, null=True)

    def __str__(self):
        """Definisce la stringa per identificare l'attività

        :return: stringa attività
        :rtype str
        """
        return self.nome

    def save(self, *args, **kwargs):
        """Aggiunge un controllo sulla reputazione prima del salvataggio nel DB

        In caso il controllo fallisca, viene sollevato un `ValueError`

        Params:
            :param args: lista variabile di argomenti da passare al metodo save di django
            :param kwargs: dictionary variabile di argomenti da passare al metodo
                save di django
            :return:
        """
        if 0. <= self.reputazione <= 5.:
            super(Attivita, self).save(*args, **kwargs)
        else:
            raise ValueError("Wrong value in field 'reputazione'")

    def update_reputazione(self):
        """Aggiorna la reputazione dell'attività

        Calcola la media ponderata dei voti delle recensioni e aggiorna il DB.
        :return:
        """
        recensioni = self.recensione_set.all()
        votoxaff = 0.
        aff_tot = 0
        for r in recensioni:
            votoxaff += r.voto * r.autore.affidabilita
            aff_tot += r.autore.affidabilita

        self.reputazione = votoxaff / max(aff_tot, 1)
        self.save()

    def get_relative_tagcloud_url(self):
        """Genera e ritorna l'url relativo della tagcloud dell'attività

        :return: url relativo della tagcloud
        :rtype str
        """
        return os.path.join('attivita', 'tagcloud', str(self.id) + '.png')

    def get_absolute_tagcloud_url(self):
        """Genera e ritorna l'url assoluto della tagcloud dell'attività

        :return: url assoluto della tagcloud
        :rtype str
        """
        path = os.path.join(BASE_DIR, 'attivita', 'static', self.get_relative_tagcloud_url())
        return path

    def update_tagcloud(self):
        """Aggiorna tagcloud dell'attività"""
        create_tag_cloud(self)


def get_upload_path(instance, filename):
    """Genera e ritorna il path di un'immagine

    :param instance: oggetto contenente l'immagine
    :param filename: nome file contenente l'immagine
    :return: path immagine
    :rtype str
    """
    if instance.tagcloud:
        path = os.path.join(BASE_DIR, 'attivita', 'static', 'attivita', 'tagcloud',
                            str(instance.attivita.id)+'.png')
    else:
        num_images = Image.objects.filter(attivita__id=instance.attivita.id).count()
        ext = instance.immagine.path.split('.')[-1]
        path = os.path.join(BASE_DIR, 'attivita', 'static', 'attivita',
                            str(instance.attivita.id), '{}.{}'.format(num_images+1, ext))
    print(path)
    return path


class Image(models.Model):
    """Definisce un'immagine

    Attributi:
        attivita (ForeignKey): chiave esterna all'attività dell'immagine
        titolo (CharField)
        immagine (ImageField)
        tagcloud (BooleanField): booleano che indica se l'immagine sia una tagcloud
    """
    attivita = models.ForeignKey(Attivita, on_delete=models.CASCADE)
    titolo = models.CharField(max_length=20)
    immagine = models.ImageField(upload_to=get_upload_path)
    filename = models.CharField(max_length=250, default=None)
    tagcloud = models.BooleanField(default=False)

    def get_relative_path(self):
        """Ritorna url relativo immagine

        :return: url relativo immagine
        :rtype str
        """
        return os.path.join('attivita', str(self.attivita.id), self.filename)

eatandrate/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from notifications.models import Notification, Answer
from .forms import UserRegistrationForm, UserModifyForm
from users.models import UserProfile, OwnerProfile
from attivita.forms import AttivitaForm, TipologieForm
from Custom.AddAttivitaUtils import add_attivita


# Create your views here.
@login_required()
def my_profile(request):
    """Renderizza pagina "Il mio profilo"

    Data la richiesta con utente autenticato, viene il recuperato il profilo
    (utente o proprietario) con relative notifiche. Dopodichè, viene
    renderizzato il relativo template

    :param request: richiesta HTTP
    :return: Template renderizzato con relativo context
    """
    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden("Impossibile accedere a pagina profilo")

    context = {'utente': user}
    try:
        owner = OwnerProfile.objects.get(user=user)
    except OwnerProfile.DoesNotExist:
        owner = None

    if owner:
        # build notification set
        notifiche = Notification.objects.filter(destinatario=owner, visualizzata=False)
        context['notifiche'] = notifiche
        return render(request, 'users/my_owner_profile.html', context=context)
    else:
        # build notification set
        risposte = Answer.objects.filter(notifica__mittente=user.user_profile, visualizzata=False)
        context['risposte'] = risposte
        return render(request, 'users/my_profile.html', context=context)


def user_profile(request, pk):
    """Renderizza pagina del profilo di un utente

    :param request: richiesta HTTP
    :param pk: chiave utente
    :return: Template renderizzato con relativo context
    """
    user = User.objects.get(pk=pk)

    if not user.is_active:
        messages.info(request, "L'utente è stato cancellato")
        return HttpResponseRedirect(reverse('attivita:index'))

    if request.user == user:
        return HttpResponseRedirect(reverse('users:my_profile'))

    context = {'utente': user}
    try:
        owner = OwnerProfile.objects.get(user=user)
    except OwnerProfile.DoesNotExist:
        owner = None

    if owner:
        return render(request, 'users/owner_page.html', context=context)
    else:
        return render(request, 'users/profile_page.html', context=context)


def register(request):
    """Registra un nuovo utente

    Se richesta GET, mostra form per inserire informazioni, se POST esegue
    controllo di validità sul form, crea utente e profilo e assegna tutti i
    permessi relativi alle recensioni

    :param request: richiesta HTTP
    :return: Template renderizzato o redirezione a pagina del profilo
    """
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            userprofile = UserProfile(user=user)
            userprofile.save()

            content_type = ContentType.objects.get(model='recensione')
            permission1 = Permission.objects.get(content_type=content_type,
                                                 codename='add_recensione')
            permission2 = Permission.objects.get(content_type=content_type, codename='can_vote_review')
            permission3 = Permission.objects.get(content_type=content_type,
                                                 codename='delete_recensione')
            permission4 = Permission.objects.get(content_type=content_type,
                                                 codename='change_recensione')

            user.user_permissions.add(permission1, permission2, permission3, permission4)
            login(request, user)
            messages.success(request, 'Utente registrato con successo!')
            return HttpResponseRedirect(reverse('users:my_profile'))
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'users/register.html', {'form': form})
    else:
        form = UserRegistrationForm()
        return render(request, 'users/register.html', {'form': form})


def register_owner(request):
    """Registra un nuovo proprietario e la relativa attività

    Se richiesta GET, mostra form per inserire informazioni proprietario,
    informazioni attività e relative tipologie, se richiesta POST controlla
    la validità dei form, crea nuovo utente e relativo profilo proprietario,
    crea l'attività e la associa alle tipologie selezionate.

    :param request: richiesta HTTP
    :return: redirezione alla pagina del profilo o renderizza template registrazione
    """
    if request.method == 'POST':
        uf = UserRegistrationForm(request.POST, prefix='user')
        af = AttivitaForm(request.POST, prefix='attivita')
        tf = TipologieForm(request.POST, prefix='tipologie')
        if uf.is_valid() and af.is_valid() and tf.is_valid():
            uf.save()
            username = uf.cleaned_data.get('username')
            raw_password = uf.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            op = OwnerProfile(user=user)
            op.save()
            add_attivita(af, op, tf)

            content_type = ContentType.objects.get(model='attivita')
            permission1 = Permission.objects.get(content_type=content_type,
                                                 codename='add_attivita')
            permission2 = Permission.objects.get(content_type=content_type,
                                                 codename='delete_attivita')
            permission3 = Permission.objects.get(content_type=content_type,
                                                 codename='change_attivita')
            user.user_permissions.add(permission1, permission2, permission3)
            login(request, user)
            messages.success(request, 'Proprietario e attività registrati con successo!')
            return HttpResponseRedirect(reverse('users:my_profile'))
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'users/register_owner.html', {'uf': uf, 'af': af, 'tf': tf,
                                                                 'error_msg': 'Invalid form'})
    else:
        uf = UserRegistrationForm(prefix='user')
        af = AttivitaForm(prefix='attivita')
        tf = TipologieForm(prefix='tipologie')
        return render(request, 'users/register_owner.html', {'uf': uf, 'af': af, 'tf': tf})


def modify_profile(request):
    """Gestisce modifica dei dati di un utente

    Se richiesta GET mostra form di modifica, se richiesta POST controlla i
    form e salva modifiche nel DB.

    :param request: richiesta HTTP
    :return: renderizza template o redireziona a pagina del profilo
    """
    if request.method == 'POST':
        form = UserModifyForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profilo modificato con successo")
            return HttpResponseRedirect(reverse('users:my_profile'))
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'users/modify_profile.html', {'form': form})
    else:
        form = UserModifyForm(instance=request.user)
        return render(request, 'users/modify_profile.html', {'form': form})


def delete_profile(request):
    """Elimina utente

    Non avviene la cancellazione dell'utente del DB per preservare le relative
    recensioni o attività, ma viene settato il flag `is_active` a False, in
    modo che non possa più loggarsi.

    :param request: richiesta HTTP
    :return: redirezione alla homepage
    """
    if request.user.is_authenticated:
        request.user.is_active = False
        request.user.save()
        logout(request)
        messages.success(request, "Profilo eliminato")
    else:
        messages.error(request, "Errore: non sei loggato!")

    return HttpResponseRedirect(reverse('attivita:index'))

eatandrate/users/templates/users/modify_profile.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block head %}
    <title>Modifica Profilo</title>
{% endblock %}

{% block content %}
    {% if error_msg %}
        <h2>{{ error_msg }}</h2>
    {% endif %}
    <div align="center">
        <h3 style="margin-top:10px">Modifica Utente</h3>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form|as_bootstrap }}
            <input class="btn btn-default" type="submit" value="Applica Modifiche" style="padding:6px 30px">
        </form>
    </div>
{% endblock %}

eatandrate/users/templates/users/my_owner_profile.html
{% extends 'base_user.html' %}

{% block head %}
    <title>Il mio profilo</title>
{% endblock %}

{% block header %}
    <h1 style="margin-top:10px">Il mio profilo | {{ utente.username | capfirst }}</h1>
{% endblock %}

{% block manage_profile %}
    <a href="{% url 'users:modify_profile' %}">
        <input class="btn btn-default" value="Modifica Profilo" style="padding:6px 30px">
    </a>
    <a href="{% url 'attivita:add' %}">
        <input class="btn btn-default" value="Aggiungi Attività" style="padding: 6px 15px">
    </a>
{% endblock %}

{% block profile_info %}
    <h2>ATTIVITA GESTITE:</h2>
    {% for att in utente.owner_profile.attivita_set.all %}
        <p><a href="{% url 'attivita:detail' att.id%}">{{ att.nome }}</a></p>
    {% endfor %}
{% endblock %}

{% block notifications %}
<div class="btn-group">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Notifiche
    <span class="caret"></span></button>
    <ul class="dropdown-menu" style="height:175px;width:250px;overflow-y:auto;overflow-x:auto">
    {% if notifiche %}
        {% for n in notifiche %}
            <li>
                <div class="row-fluid">
                    {{ n.mittente.user.username }} ha recensito {{ n.recensione.attivita.nome }}
                </div>
                <div class="row-fluid" align="center">
                    <a href="{% url 'notifications:reply' n.id %}">
                        <input class="btn btn-default" value="Reply" style="width:65px">
                    </a>
                    <a href="{% url 'notifications:delete_notification' n.id %}">
                        <input class="btn btn-default" value="X" style="width:65px">
                    </a>
                </div>
                <div class="divider"></div>
            </li>
        {% endfor %}

    {% else %}
        <li>
            <div align="center">Nessuna notifica in entrata</div>
        </li>
    {% endif %}
    </ul>
</div>
{% endblock %}

{% block delete_profile %}
<div align="center" style="margin-top:30px">
    <a href="{% url 'users:delete_profile' %}">
        <input class="btn btn-default" value="Elimina Profilo" onclick="return confirm('Are you sure?');" style="padding:6px 30px">
    </a>
</div>
{% endblock %}

eatandrate/users/templates/users/my_profile.html
{% extends 'base_user.html' %}

{% block head %}
    <title>Il mio profilo</title>
{% endblock %}

{% block header %}
    <h1 style="margin-top:10px">Il mio profilo | {{ utente.username | capfirst }}</h1>
{% endblock %}

{% block manage_profile %}
    <a href="{% url 'users:modify_profile' %}">
        <input class="btn btn-default" value="Modifica Profilo" style="padding:6px 5px">
    </a>
{% endblock %}

{% block profile_info %}
    <h2>AFFIDABILITA: {{ utente.user_profile.affidabilita }}</h2>
{% endblock %}

{% block notifications %}
<div class="btn-group">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Notifiche
    <span class="caret"></span></button>
    <ul class="dropdown-menu" style="height:175px;width:250px;overflow-y:auto;overflow-x:auto">
    {% if risposte %}
    {% for r in risposte %}
        <li>
            <p>{{ r.notifica.destinatario }} ha risposto alla tua recensione:
                <a href="{% url 'notifications:delete_answer' r.id %}">
                    <input class="btn btn-default" value="X" style="width:65px">
                </a>
            </p>
            <p style="padding-left: 10px">{{ r.risposta }}</p>
            <div class="divider"></div>
        </li>
    {% endfor %}
    {% else %}
        <li>
            <div align="center">Nessuna notifica in entrata</div>
        </li>
    {% endif %}
  </ul>

</div>
{% endblock %}

{% block delete_profile %}
    <div align="center" style="margin-top:30px">
        <a href="{% url 'users:delete_profile' %}">
            <input class="btn btn-default" value="Emilina Profilo" onclick="return confirm('Are you sure?');" style="padding:6px 30px">
        </a>
    </div>
{% endblock %}

eatandrate/users/templates/users/owner_page.html
{% extends 'base_user.html' %}

{% block header %}
    <h1>Profilo di {{ utente.username | capfirst }}</h1>
{% endblock %}

{% block profile_info %}
   <h2>ATTIVITA GESTITE:</h2>
        {% for att in utente.owner_profile.attivita_set.all %}
            <p align="center"><a href="{% url 'attivita:detail' att.id%}">{{ att.nome }}</a></p>
        {% endfor %}
{% endblock %}

eatandrate/users/templates/users/profile_page.html
{% extends 'base_user.html' %}

{% block header %}
    <h1>Profilo di {{ utente.username | capfirst }}</h1>
{% endblock %}

{% block profile_info %}
    <h2>AFFIDABILITA: {{ utente.user_profile.affidabilita }}</h2>
{% endblock %}

eatandrate/users/templates/users/register.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block head %}
    <title>Registration</title>
{% endblock %}

{% block content %}
{% if error_msg %}
    <h2>{{ error_msg }}</h2>
{% endif %}

<div align="center">
    <h3 style="margin-top:10px">Registrazione Utente</h3>
    <form method="POST" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <input class="btn btn-default" type="submit" value="Invia" style="padding:6px 30px;margin-bottom: 20px">
    </form>
</div>
{% endblock %}

eatandrate/users/templates/users/register_owner.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block head %}
    <title>Registrazione Proprietario</title>
{% endblock %}

{% block content %}
    {% if error_msg %}
        <h2>{{ error_msg }}</h2>
    {% endif %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12" align="center"><h3 style="margin-top:10px">Registrazione Attività</h3></div>
        </div>

        <form method="POST" action="{% url 'users:register_owner' %}">
            {% csrf_token %}
            <div class="col-md-1" align="center"></div>
            <div class="col-md-4" align="center">
                <div class="row">
                    <div class="col-md-4" align="center"></div>
                    <div class="col-md-8" align="center"><h3>Dati Utente</h3></div>
                    <div class="row-fluid">
                        <div class="col-md-4" align="center"></div>
                        <div class="col-md-8" align="center">  {{ uf|as_bootstrap }} </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5" align="center">
                <div class="row">
                    <div class="col-md-12" align="center"><h3>Dati Attività</h3></div>
                </div>
                <div class="row">
                    <div class="col-md-6" align="center">  {{ af|as_bootstrap }} </div>
                    <div class="col-md-6" align="center">
                        {{ tf|as_bootstrap }}
                        <input class="btn btn-default" type="submit" value="Invia" style="padding:6px 30px"></div>
                </div>
            </div>
            <div class="col-md-2" align="center"></div>
        </form>
    </div>
{% endblock %}