eatandrate/eatandrate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^admin/', admin.site.urls),
    url(r'^att/', include('attivita.urls', namespace='attivita')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^src/', include('search.urls', namespace='search')),
    url(r'^rec/', include('recensioni.urls', namespace='recensioni')),
]

eatandrate/search/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^simple_search/', views.simple_search, name='simple_search'),
    url(r'^(?P<pk>[\d]+)/simple_results/$', views.simple_results, name='simple_results'),
    url(r'^complex_search/', views.complex_search, name='complex_search'),
    url(r'^(?P<pk>[\d]+)/complex_results/$', views.complex_results, name='complex_results'),
]

eatandrate/users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import logout
from django.contrib.auth.views import login

from users.forms import MyAuthenticationForm
from . import views
from eatandrate.settings import LOGOUT_REDIRECT_URL


urlpatterns = [
    url(r'^(?P<pk>[\d]+)/$', views.user_profile, name='user_profile'),
    url(r'^myprofile/$', views.my_profile, name='my_profile'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^login/$', login, {'template_name': 'registration\login.html',
                             'authentication_form': MyAuthenticationForm}, name="login"),
    url(r'^logout/$', logout, {'next_page': LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^registerowner/$', views.register_owner, name='register_owner'),
    url(r'^modify_profile/$', views.modify_profile, name='modify_profile'),
    url(r'^delete_profile/$', views.delete_profile, name='delete_profile'),
]

eatandrate/templates/base.html
<!DOCTYPE html>

<html lang="en" style="position:relative;min-height:100%;margin:0;padding:0">
<head>
    <meta charset="UTF-8">
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Adjust login form width -->
    <style>
        .form-control {
            width: auto;
        }
    </style>
</head>
<body style=" background-color:#e6f0ff;margin:0;padding:0">
  <div class="pageContentWrapper" style="margin-bottom:40px">
      <nav class="navbar navbar-default">
		  <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavBar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/att">EATANDRATE</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="myNavBar">
                  <form class="navbar-form navbar-left" method="post" action="{% url 'search:simple_search' %}">
                      {% csrf_token %}
                      <div class="form-group">
                        <input type="text" for="btn_cerca" class="form-control" placeholder="Ricerca su EatAndDrate" name="testo_ricerca" style="width:auto">
                      </div>
                      <button type="submit" class="btn btn-default" name="btn_cerca">Cerca</button>
                  </form>

                  <ul class="nav navbar-nav navbar-right">
                      {% if request.user.is_authenticated %}
                            <li><a href="{% url 'users:my_profile' %}"> Il mio profilo </a></li>
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                      {% else %}
                            <li><a href="{% url 'users:register_owner' %}">Ho un'attività</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Accesso<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'users:login' %}">Login</a></li>
                                    <li><a href="{% url 'users:register' %}">Registrati</a></li>
                                </ul>
                            </li>
                      {% endif %}
                  </ul>
              </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
      </nav>

      {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
      {% endif %}

      {% block content %}{% endblock %}

      <div class="fixed-bottom">
          <div style="padding:1em;position:absolute;bottom:0;width:100%;text-align:right;background-color:#b3d1ff;height:40px;font:menu;padding-top:12px;">
              <p>©2018 Developed with Django</p>
          </div>
      </div>
  </div>

  <!-- Load JavaScript -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  {% block javascript %}{% endblock %}

</body>
</html>

eatandrate/templates/base_user.html
{% extends 'base.html' %}
{% block head %}
    <title>Profilo</title>
{% endblock %}
{% block content %}
    <div align="center">
        {% block header %}{% endblock %}
        {% block manage_profile %}{% endblock %}
        {% block profile_info %}{% endblock %}
        {% block notifications %}{% endblock %}
    </div>
    <div align="center">
        <h3>Dati:</h3>
        <div align="center">
            {% if utente.first_name %}
                <p>{{ utente.first_name }}</p>
            {% endif %}
            {%  if utente.last_name %}
                <p>{{ utente.last_name }}</p>
            {% endif %}
                <p>{{ utente.email }}</p>
        </div>
    </div>

    {% block delete_profile %}{% endblock %}
{% endblock %}