eatandrate/attivita/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[\d]+)/$', views.AttView.as_view(), name='detail'),
    url(r'^(?P<pk>[\d]+)/recensisci$', views.recensisci, name='recensisci'),
    url(r'^(?P<pk>[\d]+)/modify$', views.modify, name='modify'),
    url(r'^(?P<pk>[\d]+)/add_image$', views.add_image, name='add_image'),
    url(r'^add/$', views.add, name='add'),
    url(r'^(?P<pk>[\d]+)/delete_image$', views.delete_image, name='delete_image')
]

eatandrate/eatandrate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^admin/', admin.site.urls),
    url(r'^att/', include('attivita.urls', namespace='attivita')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^src/', include('search.urls', namespace='search')),
    url(r'^rec/', include('recensioni.urls', namespace='recensioni')),
]

eatandrate/recensioni/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[\d]+)/vote_pos$', views.vote_pos, name='vote_pos'),
    url(r'^(?P<pk>[\d]+)/vote_neg$', views.vote_neg, name='vote_neg'),
]

eatandrate/users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import logout
from django.contrib.auth.views import login

from users.forms import MyAuthenticationForm
from . import views
from eatandrate.settings import LOGOUT_REDIRECT_URL


urlpatterns = [
    url(r'^(?P<pk>[\d]+)/$', views.user_profile, name='user_profile'),
    url(r'^myprofile/$', views.my_profile, name='my_profile'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^login/$', login, {'template_name': 'registration\login.html',
                             'authentication_form': MyAuthenticationForm}, name="login"),
    url(r'^logout/$', logout, {'next_page': LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^registerowner/$', views.register_owner, name='register_owner'),
    url(r'^modify_profile/$', views.modify_profile, name='modify_profile'),
    url(r'^delete_profile/$', views.delete_profile, name='delete_profile'),
]

eatandrate/attivita/models.py
"""Definisce i modelli per l'app `attivita`

Modelli:
    Tipologia
    Attività
    Immagine

Funzioni:
    get_upload_path
"""
import os

from users.models import OwnerProfile
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from eatandrate.settings import BASE_DIR
from Custom.Utilities import create_tag_cloud


# Create your models here.
class Tipologia(models.Model):
    """Definisce una tipologia attribuibile ad un'attività

    Attributi:
        nome (CharField): nome della tipologia
    """
    nome = models.CharField('nome', max_length=25, unique=True, default='Useless Tipology')

    def __str__(self):
        """Definisce la stringa per identificare la tipologia

        :return: stringa tipologia
        :rtype str
        """
        return self.nome


class Attivita(models.Model):
    """Definisce un'attività

    Attributi:
        nome (CharField)
        indirizzo (CharField)
        citta (CharField)
        reputazione (FloatField): punteggio dell'attività basato sulle
            recensioni ricevute
        descrizione (TextField)
        proprietario (ForeignKey): chiave esterna al profilo di un proprietario
        tipologie (ManyToManyField): riferimento alle tipologie dell'attività
        latitudine (FloatField)
        longitudine (FloatField)
    :return
    """
    nome = models.CharField('Nome', max_length=50)
    indirizzo = models.CharField('Indirizzo', max_length=50)
    citta = models.CharField('Città', max_length=30)
    reputazione = models.FloatField('Reputazione', default=0,
                                    validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    descrizione = models.TextField('Descrizione', blank=True,
                                   max_length=500)
    proprietario = models.ForeignKey(OwnerProfile, on_delete=models.CASCADE, null=True)
    tipologie = models.ManyToManyField(Tipologia, blank=True)
    latitudine = models.FloatField('Latitudine', blank=True, null=True)
    longitudine = models.FloatField('Longitudine', blank=True, null=True)

    def __str__(self):
        """Definisce la stringa per identificare l'attività

        :return: stringa attività
        :rtype str
        """
        return self.nome

    def save(self, *args, **kwargs):
        """Aggiunge un controllo sulla reputazione prima del salvataggio nel DB

        In caso il controllo fallisca, viene sollevato un `ValueError`

        Params:
            :param args: lista variabile di argomenti da passare al metodo save di django
            :param kwargs: dictionary variabile di argomenti da passare al metodo
                save di django
            :return:
        """
        if 0. <= self.reputazione <= 5.:
            super(Attivita, self).save(*args, **kwargs)
        else:
            raise ValueError("Wrong value in field 'reputazione'")

    def update_reputazione(self):
        """Aggiorna la reputazione dell'attività

        Calcola la media ponderata dei voti delle recensioni e aggiorna il DB.
        :return:
        """
        recensioni = self.recensione_set.all()
        votoxaff = 0.
        aff_tot = 0
        for r in recensioni:
            votoxaff += r.voto * r.autore.affidabilita
            aff_tot += r.autore.affidabilita

        self.reputazione = votoxaff / max(aff_tot, 1)
        self.save()

    def get_relative_tagcloud_url(self):
        """Genera e ritorna l'url relativo della tagcloud dell'attività

        :return: url relativo della tagcloud
        :rtype str
        """
        return os.path.join('attivita', 'tagcloud', str(self.id) + '.png')

    def get_absolute_tagcloud_url(self):
        """Genera e ritorna l'url assoluto della tagcloud dell'attività

        :return: url assoluto della tagcloud
        :rtype str
        """
        path = os.path.join(BASE_DIR, 'attivita', 'static', self.get_relative_tagcloud_url())
        return path

    def update_tagcloud(self):
        """Aggiorna tagcloud dell'attività"""
        create_tag_cloud(self)


def get_upload_path(instance, filename):
    """Genera e ritorna il path di un'immagine

    :param instance: oggetto contenente l'immagine
    :param filename: nome file contenente l'immagine
    :return: path immagine
    :rtype str
    """
    if instance.tagcloud:
        path = os.path.join(BASE_DIR, 'attivita', 'static', 'attivita', 'tagcloud',
                            str(instance.attivita.id)+'.png')
    else:
        num_images = Image.objects.filter(attivita__id=instance.attivita.id).count()
        ext = instance.immagine.path.split('.')[-1]
        path = os.path.join(BASE_DIR, 'attivita', 'static', 'attivita',
                            str(instance.attivita.id), '{}.{}'.format(num_images+1, ext))
    print(path)
    return path


class Image(models.Model):
    """Definisce un'immagine

    Attributi:
        attivita (ForeignKey): chiave esterna all'attività dell'immagine
        titolo (CharField)
        immagine (ImageField)
        tagcloud (BooleanField): booleano che indica se l'immagine sia una tagcloud
    """
    attivita = models.ForeignKey(Attivita, on_delete=models.CASCADE)
    titolo = models.CharField(max_length=20)
    immagine = models.ImageField(upload_to=get_upload_path)
    filename = models.CharField(max_length=250, default=None)
    tagcloud = models.BooleanField(default=False)

    def get_relative_path(self):
        """Ritorna url relativo immagine

        :return: url relativo immagine
        :rtype str
        """
        return os.path.join('attivita', str(self.attivita.id), self.filename)

eatandrate/attivita/views.py
import os
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.utils import timezone
from django.views import generic
from django.contrib.auth.decorators import permission_required
from django.contrib import messages

from users.models import UserProfile
from .models import Attivita, Image, Tipologia, get_upload_path
from recensioni.models import Recensione
from .forms import AttivitaForm, UploadImageForm, TipologieForm
from recensioni.forms import RecensioneForm
from Custom.TipologieUtils import add_tipe_object
from Custom.Utilities import get_consigliati
from Custom.AddAttivitaUtils import update_coordinates_from_address, add_attivita


# Create your views here.
def index(request):
    """Genera i contenuti della homepage del sito e renderizza il template
    :param request: richiesta HTTP della pagina
    :return: Template renderizzato con il context generato
    """
    context = dict()
    context['top_attivita_list'] = Attivita.objects.order_by('-reputazione')[:5]
    context['top_user_list'] = UserProfile.objects.order_by('-affidabilita')[:5]
    if request.user.is_authenticated and not request.user.is_superuser:
        try:
            profile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            profile = None

        if profile:
            context['consigliati'] = get_consigliati(request)

    return render(request, 'attivita/index.html', context)


class AttView(generic.DetailView):
    """Generic view della pagina dettaglio di una singola attività"""
    model = Attivita
    template_name = 'attivita/detail.html'

    def get_context_data(self, **kwargs):
        """Calcola e ritorna il context da passare al template"""
        context = super().get_context_data(**kwargs)
        context['recensioni'] = Recensione.objects.filter(attivita=self.object).order_by('-data')
        return context


@permission_required('recensioni.add_recensione')
def recensisci(request, pk):
    """Gestisce la richiesta di recensire un'attività

    Se richiesta GET, mostra il form da compilare, se richiesta POST controlla
    la correttezza del form e se sbagliato ricarica la pagina notificando gli
    errori, se giusto crea la recensione e reindirizza alla pagina dell'attività

    :param request: richiesta HTTP della pagina
    :param pk: id attività da recensire
    :return: Template renderizzato con il context generato
    """
    attivita = get_object_or_404(Attivita, pk=pk)
    if request.user in [r.autore.user for r in attivita.recensione_set.all()]:
        messages.error(request, "Hai già recensito questa attività")
        return HttpResponseRedirect(reverse('attivita:detail', args=(attivita.id,)))

    if request.method == 'GET':
        form = RecensioneForm()
        return render(request, 'attivita/recensisci.html', {'form': form, 'pk': pk})
    else:  # richiesta POST
        # Salvataggio recensione (uso form bound)
        form = RecensioneForm(request.POST)
        if form.is_valid():
            data = timezone.now().date()
            attivita.recensione_set.create(attivita=attivita, autore=request.user.user_profile,
                                           data=data,
                                           voto=form.cleaned_data.get('voto'),
                                           testo=form.cleaned_data.get('testo'))
            attivita.update_reputazione()
            attivita.update_tagcloud()
            messages.success(request, "Attività recensita, grazie della tua recensione!")
            return HttpResponseRedirect(reverse('attivita:detail', args=(pk,)))
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'attivita/recensisci.html', {'form': form, 'pk': pk})


@permission_required('attivita.change_attivita')
def modify(request, pk):
    """Gestisce la richiesta di modifica di un'attività

    Se richiesta GET, mostra il form di modifica, se richiesta POST, controlla
    validità del form e salva le nuove informazioni nel DB.

    :param request: richiesta HTTP
    :param pk: id attività da modificare
    :return: Template renderizzato con il context generato
    """
    att = get_object_or_404(Attivita, pk=pk)
    if request.user != att.proprietario.user:
        return HttpResponseForbidden("L'utente loggato non può modificare l'attività")

    if request.method == 'POST':
        if 'attivitainfo' in request.POST:
            form = AttivitaForm(request.POST, instance=att)
            if form.is_valid():
                new_att = form.save()
                update_coordinates_from_address(new_att)
                messages.success(request, "Attività modificata")
                return HttpResponseRedirect(reverse('attivita:modify', args=(pk,)))
            else:
                messages.error(request, "Errore nella compilazione del form")
                return render(request, 'attivita/modifica.html', {'form': form, 'pk': pk})
        elif 'tipologieinfo' in request.POST:
            form = TipologieForm(request.POST)
            if form.is_valid():
                if form.has_changed():
                    add_tipe_object(att, form)
                    messages.success(request, "Tipologie attività aggiornate")
                return HttpResponseRedirect(reverse('attivita:modify', args=(att.id,)))
            else:
                messages.error(request, "Errore nella compilazione del form")
                return render(request, 'attivita/modifica.html', {'form': form, 'pk': pk})
    else:
        attform = AttivitaForm(att.__dict__)
        # Inizializzo checkbox tipologie
        data = {}
        for t in Tipologia.objects.all():
            data[t.nome] = (t in att.tipologie.all())
        tipform = TipologieForm(data)
        return render(request, 'attivita/modifica.html', {'attform': attform,
                                                          'tipform': tipform,
                                                          'pk': pk,
                                                          'attivita': att})


@permission_required('attivita.add_attivita')
def add(request):
    """Gestisce la richiesta di aggiunta di un'attività.

    Se richiesta GET, mostra il form di aggiunta informazioni e tipologie, se
    richiesta POST controlla la correttezza dei form e crea nuova attività.

    :param request: richiesta HTTP
    :return: Template renderizzato con il context generato
    """
    if request.method == 'POST':
        attform = AttivitaForm(request.POST, prefix='attivita')
        tipform = TipologieForm(request.POST, prefix='tipologie')
        if attform.is_valid() and tipform.is_valid() and request.user.owner_profile:
            att = add_attivita(attform, request.user.owner_profile, tipform)
            if att:
                messages.success(request, "Attività aggiunta con successo")
                return HttpResponseRedirect(reverse('attivita:detail', args=(att.id,)))
            else:
                messages.error(request, "Qualcosa è andato storto :(")
                return HttpResponseBadRequest('Qualcosa è andato storto :(')
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'attivita/add.html', {'attform': attform, 'tipform': tipform})
    else:
        attform = AttivitaForm(prefix='attivita')
        tipform = TipologieForm(prefix='tipologie')
        return render(request, 'attivita/add.html', {'attform': attform, 'tipform': tipform})


@permission_required('attivita.change_attivita')
def add_image(request, pk):
    """Gestisce aggiunta immagine

    :param request: richiesta HTTP
    :param pk: id attività di cui aggiungere l'immagine
    :return: Template renderizzato con il context generato
    """
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.save(commit=False)
            img.attivita = get_object_or_404(Attivita, pk=pk)
            img.filename = os.path.split(get_upload_path(img, None))[-1]
            img.save()
            messages.success(request, "Immagine aggiunta all'attività")
            return HttpResponseRedirect(reverse('attivita:modify', args=(pk,)))
        else:
            messages.error(request, "Errore nella compilazione del form")
            return render(request, 'attivita/upload_image.html', {'pk': pk, 'form': form})
    else:
        form = UploadImageForm()
        return render(request, 'attivita/upload_image.html', {'pk': pk, 'form': form})


@permission_required('attivita.change_attivita')
def delete_image(request, pk):
    """Gestisce eliminazione immagine

    :param request: richiesta HTTP
    :param pk: id immagine da eliminare
    :return: redirezione alla pagina di modifica attività
    """
    img = get_object_or_404(Image, pk=pk)
    img.delete()
    messages.success(request, "Immagine rimossa")
    return HttpResponseRedirect(reverse('attivita:modify', args=(img.attivita.id,)))

eatandrate/attivita/templates/attivita/add.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block head %}
    <title>Aggiungi Attività</title>
{% endblock %}
{% block content %}
<div align="center">
    {% if error_msg %}
    <h3>{{ error_msg }}</h3>
    {% endif %}
    <form method="post" action="{% url 'attivita:add' %}">{% csrf_token %}
      <div class="row-fluid">
      <div class="col-md-12" align="center"><h3 style="margin-bottom:35px">Aggiungi Attività</h3></div>
      </div>
      <div class="row-fluid">
          <div class="col-md-3" align="center"></div>
          <div class="col-md-3" align="center">  {{ attform|as_bootstrap }}</div>
          <div class="col-md-3" align="center">  {{ tipform|as_bootstrap }}
            <input class="btn btn-default" type="submit" value="Aggiungi" style="padding:6px 30px">
          </div>
          <div class="col-md-3" align="center"></div>
      </div>
    </form>
</div>
{% endblock %}

eatandrate/attivita/templates/attivita/detail.html
{% extends "base.html" %}

{% block head %}
    <title>{{ attivita.nome }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row-fluid">
      <div class="col-md-12" align="center">
        <h1>{{ attivita.nome }}    |    REP: {{ attivita.reputazione | floatformat }}</h1>
      </div>
  </div>
  <div class="col-md-1" align="center"></div>
  <div class="col-md-4" align="center">
      <div class="row">
          <div class="col-md-4" align="center"></div>
          <div class="col-md-8" align="center"><h3>Dati Locale</h3></div>
          <div class="row-fluid">
              <div class="col-md-4" align="center"></div>
              <div class="col-md-8" align="center">
                 <p>{{ attivita.citta }}, {{ attivita.indirizzo }}</p>
                 <p>Proprietario:
                     <a href="{% url 'users:user_profile' attivita.proprietario.user.id %} ">
                     {{ attivita.proprietario.user.username }}</a></p>
                 {% if attivita.tipologie.count > 0 %}
                     <p>|
                     {% for t in attivita.tipologie.all %}
                        {{ t.nome }} |
                     {% endfor %}
                     </p>
                 {% endif %}
                 <p>{{ attivita.descrizione }}</p>
                 {% if request.user.owner_profile == attivita.proprietario %}
                    <a href="{% url 'attivita:modify' attivita.id %}">
                    <input class="btn btn-default" value="Modifica Attività" style="padding: 6px 15px">
                    </a>
                 {% endif %}
            </div>
        </div>
      </div>
  </div>
  <div class="col-md-5" align="center">
      <div class="row">
          <div class="col-md-12" align="center"><h3>Recensioni</h3></div>
      </div>
          {% if recensioni %}
              <div class="row-fluid" style="overflow-y:auto;height:215px">
                  {% if error_rec_msg %}
                      <p style="color: red">{{ error_rec_msg }}</p>
                  {% endif %}

                  {% for r in recensioni %}
                    <div class="col-md-8">
                    <p>
                      <h4><a href="{% url 'users:user_profile' r.autore.user.id %}">{{ r.autore.user.username }}</a>
                          | Voto: {{ r.voto }}</h4>
                      <h6>{{ r.data }}</h6>
                      <p>{{ r.testo }}</p>
                    </div>
                    <div class="col-md-4">
                        <div class="col-md-5">
                            <a href="{% url 'recensioni:vote_pos' r.id %}">
                                <button type="button" class="btn btn-default" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                                </button>
                            </a>
                        </div>
                        <div class="col-md-3">
                            {{ r.utilita }}
                        </div>
                        <div class="col-md-2">
                            <a href="{% url 'recensioni:vote_neg' r.id %}">
                                <button type="button" class="btn btn-default" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                                </button>
                            </a>
                        </div>
                    </div>
                  {% endfor %}
              </div>
          {% else %}
              <div class="row-fluid">
                  <div class="col-md-12">
                      <h4>Nessuna Recensione</h4>
                  </div>
              </div>
          {% endif %}

      <div class="row-fluid">
          <a class="btn btn-default" href="{% url 'attivita:recensisci' attivita.id %}" style="margin-top:15px">Scrivi recensione</a>
      </div>
  </div>

</div>
    <div class="col-md-2" align="center"></div>

  <div class="row-fluid">
  <div class="col-md-12" align="center"><h3>Immagini</h3></div>
  <div class="row-fluid">
  <div class="col-md-4" align="center"></div>
  <div class="col-md-4" align="center" style="margin-bottom: 30px">
    {% if attivita.image_set.count > 0 %}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              {% with attivita.image_set.all|first as img %}
              {% load static %}
              <img src="{% static img.get_relative_path %}" style="height:250px">
              {% endwith %}
            </div>
              {% for img in attivita.image_set.all|slice:"1:" %}
                <div class="item">
                  {% load static %}
                  <img src="{% static img.get_relative_path %}" style="height:250px">
                </div>
              {% endfor %}
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    {% else %}
        <h4>Nessuna immagine disponibile</h4>
    {% endif %}
  </div>
    <div class="col-md-4" align="center"></div>
  </div>
  </div>
    {% if recensioni %}
    <div class="row-fluid">
        <div class="col-md-12" align="center"><h3 style="margin-top:10px"><h3>Tag Cloud</h3></div>
    </div>
    <div class="row-fluid">
        <div class="row-fluid">
            <div class="col-md-12" align="center" style="margin-bottom: 30px">
              <button class="btn btn-default" onclick="toggleView()" style="margin-bottom: 15px">Show/Hide TagCloud</button>
            </div>
        </div>
        <div class="col-md-12" align="center">
          {% load static %}
              <img id ="tagCloud" src="{% static attivita.get_relative_tagcloud_url %}"
                  style="display: none; margin-bottom: 50px; width: 80%;">
        </div>
    </div>
    {% endif %}
    <div class="row-fluid">
        <div class="col-md-12" align="center">
          {% if attivita.longitudine and attivita.latitudine %}
              <div id="googleMap" style="width:70%;height:300px;margin-bottom:70px"></div>
          {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
          <script>
              function toggleView() {
                  var x = document.getElementById("tagCloud");
                  if (x.style.display === "none") {
                      x.style.display = "block";
                  } else {
                      x.style.display = "none";
                  }
              }

              {% if attivita.latitudine and attivita.longitudine %}
                  function myMap() {
                      var mapProp= {
                        center:new google.maps.LatLng({{ attivita.latitudine }}, {{ attivita.longitudine }}),
                        zoom:15
                      };
                      var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
                      var marker = new google.maps.Marker({
                        position: {lat: {{ attivita.latitudine }}, lng: {{ attivita.longitudine }} },
                        map: map
                      });
                  }
              {% endif %}
          </script>
          {% if attivita.latitudine and attivita.longitudine %}
              <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgd9efyE6IDhqujcNVWDnJFztZllr21Co&callback=myMap"></script>
          {% endif %}
{% endblock %}

eatandrate/attivita/templates/attivita/modifica.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block head %}
    <title>Modifica</title>
{% endblock %}
{% block content %}
    <div align="center">
        <a href="{% url 'attivita:detail' attivita.id %}">Torna a {{ attivita.nome | capfirst }}</a>

        <div class="row-fluid">
        <div class="col-md-12" align="center"><h3>Dati Attività</h3></div>
        </div>
        {% if error_msg %}
        <h3>{{ error_msg }}</h3>
        {% endif %}
        <div class="row-fluid">
            <form method="post" action="{% url 'attivita:modify' pk %}">
                {% csrf_token %}
                <div class="col-md-3" align="center"></div>
                <div class="col-md-3" align="center">  {{ attform|as_bootstrap }}
                    <input class="btn btn-default" type="submit" name="attivitainfo" value="Aggiorna Informazioni" style="padding:6px 10px"/>
                </div>
                <div class="col-md-3" align="center">
                    {{ tipform|as_bootstrap }}
                    <input class="btn btn-default" type="submit" name="tipologieinfo" value="Aggiorna tipologie" style="padding:6px 10px"/>
                </div>
                <div class="col-md-3" align="center"></div>
            </form>
        </div>

        <div class="row-fluid">
            <div class="col-md-12" align="center"><h3>Immagini</h3></div>
            <div class="col-md-12">
                <a href="{% url 'attivita:add_image' attivita.id %}">
                  <input class="btn btn-default" value="Aggiungi Immagine" style="padding: 6px 15px;margin-bottom:45px">
                </a>
            </div>
            <div class="col-md-12" style="margin-bottom: 70px">
                {% if attivita.image_set %}
                    {% for img in attivita.image_set.all %}
                        <p>
                            {{ img.titolo }}
                            <a href="{% url 'attivita:delete_image' img.id %}"><button type="button">X</button></a>
                        </p>
                    {% endfor %}
                {% else %}
                    <p>Nessuna immagine caricata! :(</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

eatandrate/attivita/templates/attivita/recensisci.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block head %}
    <title>Scrivi Recensione</title>
{% endblock %}
{% block content %}
<div align="center">
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    <form action="{% url 'attivita:recensisci' pk %}" method="post">{% csrf_token %}
        {{ form|as_bootstrap }}
        <input class="btn btn-default" type="submit" value="Recensisci" style="padding: 6px 15px" />
    </form>
</div>
{% endblock %}

eatandrate/attivita/templates/attivita/upload_image.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block head %}
    <title>Upload</title>
{% endblock %}
{% block content %}
<div align="center">
    <form enctype="multipart/form-data" action="{% url 'attivita:add_image' pk %}" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <input class="btn btn-default" type="submit" value="Invia" style="padding:6px 30px">
    </form>
</div>
{% endblock %}